name: action lint

on:
  pull_request:
    paths:
      - .github/workflows/*.yml
      - .github/workflows/*.yaml
      - .github/actions/**
      - ghalint.yaml
      - mise.toml

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  actionlint:
    runs-on: ubuntu-latest # ubuntu-slimではdocker command not foundになるため、未対応
    timeout-minutes: 5
    permissions:
      checks: write
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: true # reviewdogのためにtrueにしている
      - uses: reviewdog/action-actionlint@1758727be30241166609dad4c97588b6ad411f32 # v1.79.1
        with:
          fail_level: warning
          filter_mode: nofilter
          level: error
          reporter: github-pr-review
  ghalint:
    runs-on: ubuntu-slim
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: jdx/mise-action@2d8d4cafcbd33be2ea37d2b6f5ad595363d1f1ca # v5.1.1
        with:
          install_args: ghalint
      - run: ghalint run
      - run: ghalint act
